spring.application.name=springbt-krb5-databases-demo

# Database Connectivity:
spring.datasource.url=jdbc:postgresql://localhost:5432/kerberosdb
spring.datasource.username=ernest@DEV.LOCAL
spring.datasource.hikari.maximum-pool-size=5
spring.sql.init.mode=never

#Logging
logging.level.org.postgresql=DEBUG
logging.level.org.springframework.jdbc=DEBUG